// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: user_service/user_service.proto

package user_servicepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpV1Request) Reset() {
	*x = SignUpV1Request{}
	mi := &file_user_service_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpV1Request) ProtoMessage() {}

func (x *SignUpV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpV1Request.ProtoReflect.Descriptor instead.
func (*SignUpV1Request) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpV1Request) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignUpV1Request) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SignUpV1Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignUpV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpV1Response) Reset() {
	*x = SignUpV1Response{}
	mi := &file_user_service_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpV1Response) ProtoMessage() {}

func (x *SignUpV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpV1Response.ProtoReflect.Descriptor instead.
func (*SignUpV1Response) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *SignUpV1Response) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type LogInV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInV1Request) Reset() {
	*x = LogInV1Request{}
	mi := &file_user_service_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInV1Request) ProtoMessage() {}

func (x *LogInV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInV1Request.ProtoReflect.Descriptor instead.
func (*LogInV1Request) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *LogInV1Request) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LogInV1Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LogInV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInV1Response) Reset() {
	*x = LogInV1Response{}
	mi := &file_user_service_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInV1Response) ProtoMessage() {}

func (x *LogInV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInV1Response.ProtoReflect.Descriptor instead.
func (*LogInV1Response) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *LogInV1Response) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type LogOutV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogOutV1Request) Reset() {
	*x = LogOutV1Request{}
	mi := &file_user_service_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogOutV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogOutV1Request) ProtoMessage() {}

func (x *LogOutV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogOutV1Request.ProtoReflect.Descriptor instead.
func (*LogOutV1Request) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{4}
}

type LogOutV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogOutV1Response) Reset() {
	*x = LogOutV1Response{}
	mi := &file_user_service_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogOutV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogOutV1Response) ProtoMessage() {}

func (x *LogOutV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogOutV1Response.ProtoReflect.Descriptor instead.
func (*LogOutV1Response) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *LogOutV1Response) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type UpdateV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Login         string                 `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateV1Request) Reset() {
	*x = UpdateV1Request{}
	mi := &file_user_service_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateV1Request) ProtoMessage() {}

func (x *UpdateV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateV1Request.ProtoReflect.Descriptor instead.
func (*UpdateV1Request) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateV1Request) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *UpdateV1Request) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateV1Request) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UpdateV1Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UpdateV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateV1Response) Reset() {
	*x = UpdateV1Response{}
	mi := &file_user_service_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateV1Response) ProtoMessage() {}

func (x *UpdateV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateV1Response.ProtoReflect.Descriptor instead.
func (*UpdateV1Response) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{7}
}

type ValidateV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateV1Request) Reset() {
	*x = ValidateV1Request{}
	mi := &file_user_service_user_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateV1Request) ProtoMessage() {}

func (x *ValidateV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateV1Request.ProtoReflect.Descriptor instead.
func (*ValidateV1Request) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateV1Request) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type ValidateV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *UserInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateV1Response) Reset() {
	*x = ValidateV1Response{}
	mi := &file_user_service_user_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateV1Response) ProtoMessage() {}

func (x *ValidateV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateV1Response.ProtoReflect.Descriptor instead.
func (*ValidateV1Response) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateV1Response) GetInfo() *UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type UploadProfileImageV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProfileImageV1Request) Reset() {
	*x = UploadProfileImageV1Request{}
	mi := &file_user_service_user_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProfileImageV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfileImageV1Request) ProtoMessage() {}

func (x *UploadProfileImageV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfileImageV1Request.ProtoReflect.Descriptor instead.
func (*UploadProfileImageV1Request) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{10}
}

func (x *UploadProfileImageV1Request) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *UploadProfileImageV1Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UploadProfileImageV1Request) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadProfileImageV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProfileImageV1Response) Reset() {
	*x = UploadProfileImageV1Response{}
	mi := &file_user_service_user_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProfileImageV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfileImageV1Response) ProtoMessage() {}

func (x *UploadProfileImageV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfileImageV1Response.ProtoReflect.Descriptor instead.
func (*UploadProfileImageV1Response) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{11}
}

func (x *UploadProfileImageV1Response) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type GetUsersInfoV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersInfoV1Request) Reset() {
	*x = GetUsersInfoV1Request{}
	mi := &file_user_service_user_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersInfoV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersInfoV1Request) ProtoMessage() {}

func (x *GetUsersInfoV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersInfoV1Request.ProtoReflect.Descriptor instead.
func (*GetUsersInfoV1Request) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetUsersInfoV1Request) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetUsersInfoV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          []*UserInfo            `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersInfoV1Response) Reset() {
	*x = GetUsersInfoV1Response{}
	mi := &file_user_service_user_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersInfoV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersInfoV1Response) ProtoMessage() {}

func (x *GetUsersInfoV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersInfoV1Response.ProtoReflect.Descriptor instead.
func (*GetUsersInfoV1Response) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetUsersInfoV1Response) GetInfo() []*UserInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ImageId       string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_service_user_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{14}
}

func (x *UserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	MaxAge        int64                  `protobuf:"varint,4,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Secure        bool                   `protobuf:"varint,5,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly      bool                   `protobuf:"varint,6,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	SameSite      int64                  `protobuf:"varint,7,opt,name=same_site,json=sameSite,proto3" json:"same_site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_user_service_user_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{15}
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Session) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Session) GetMaxAge() int64 {
	if x != nil {
		return x.MaxAge
	}
	return 0
}

func (x *Session) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

func (x *Session) GetHttpOnly() bool {
	if x != nil {
		return x.HttpOnly
	}
	return false
}

func (x *Session) GetSameSite() int64 {
	if x != nil {
		return x.SameSite
	}
	return 0
}

var File_user_service_user_service_proto protoreflect.FileDescriptor

const file_user_service_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1fuser_service/user_service.proto\x12\fchat_service\x1a\x1cgoogle/api/annotations.proto\"_\n" +
	"\x0fSignUpV1Request\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"C\n" +
	"\x10SignUpV1Response\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.chat_service.SessionR\asession\"B\n" +
	"\x0eLogInV1Request\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"B\n" +
	"\x0fLogInV1Response\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.chat_service.SessionR\asession\"\x11\n" +
	"\x0fLogOutV1Request\"C\n" +
	"\x10LogOutV1Response\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.chat_service.SessionR\asession\"\x90\x01\n" +
	"\x0fUpdateV1Request\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.chat_service.SessionR\asession\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05login\x18\x03 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\"\x12\n" +
	"\x10UpdateV1Response\"D\n" +
	"\x11ValidateV1Request\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.chat_service.SessionR\asession\"@\n" +
	"\x12ValidateV1Response\x12*\n" +
	"\x04info\x18\x01 \x01(\v2\x16.chat_service.UserInfoR\x04info\"|\n" +
	"\x1bUploadProfileImageV1Request\x12/\n" +
	"\asession\x18\x01 \x01(\v2\x15.chat_service.SessionR\asession\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"9\n" +
	"\x1cUploadProfileImageV1Response\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\")\n" +
	"\x15GetUsersInfoV1Request\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"D\n" +
	"\x16GetUsersInfoV1Response\x12*\n" +
	"\x04info\x18\x01 \x03(\v2\x16.chat_service.UserInfoR\x04info\"Z\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\"\xb2\x01\n" +
	"\aSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x17\n" +
	"\amax_age\x18\x04 \x01(\x03R\x06maxAge\x12\x16\n" +
	"\x06secure\x18\x05 \x01(\bR\x06secure\x12\x1b\n" +
	"\thttp_only\x18\x06 \x01(\bR\bhttpOnly\x12\x1b\n" +
	"\tsame_site\x18\a \x01(\x03R\bsameSite2\x94\x06\n" +
	"\vUserService\x12e\n" +
	"\bSignUpV1\x12\x1d.chat_service.SignUpV1Request\x1a\x1e.chat_service.SignUpV1Response\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user/create\x12a\n" +
	"\aLogInV1\x12\x1c.chat_service.LogInV1Request\x1a\x1d.chat_service.LogInV1Response\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/user/login\x12e\n" +
	"\bLogOutV1\x12\x1d.chat_service.LogOutV1Request\x1a\x1e.chat_service.LogOutV1Response\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user/logout\x12e\n" +
	"\bUpdateV1\x12\x1d.chat_service.UpdateV1Request\x1a\x1e.chat_service.UpdateV1Response\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/v1/user/update\x12m\n" +
	"\n" +
	"ValidateV1\x12\x1f.chat_service.ValidateV1Request\x1a .chat_service.ValidateV1Response\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/user/validate\x12\x88\x01\n" +
	"\x14UploadProfileImageV1\x12).chat_service.UploadProfileImageV1Request\x1a*.chat_service.UploadProfileImageV1Response\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/user/image\x12s\n" +
	"\x0eGetUsersInfoV1\x12#.chat_service.GetUsersInfoV1Request\x1a$.chat_service.GetUsersInfoV1Response\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/users/listB*Z(chattery/user_service/api;user_servicepbb\x06proto3"

var (
	file_user_service_user_service_proto_rawDescOnce sync.Once
	file_user_service_user_service_proto_rawDescData []byte
)

func file_user_service_user_service_proto_rawDescGZIP() []byte {
	file_user_service_user_service_proto_rawDescOnce.Do(func() {
		file_user_service_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_user_service_proto_rawDesc), len(file_user_service_user_service_proto_rawDesc)))
	})
	return file_user_service_user_service_proto_rawDescData
}

var file_user_service_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_user_service_user_service_proto_goTypes = []any{
	(*SignUpV1Request)(nil),              // 0: chat_service.SignUpV1Request
	(*SignUpV1Response)(nil),             // 1: chat_service.SignUpV1Response
	(*LogInV1Request)(nil),               // 2: chat_service.LogInV1Request
	(*LogInV1Response)(nil),              // 3: chat_service.LogInV1Response
	(*LogOutV1Request)(nil),              // 4: chat_service.LogOutV1Request
	(*LogOutV1Response)(nil),             // 5: chat_service.LogOutV1Response
	(*UpdateV1Request)(nil),              // 6: chat_service.UpdateV1Request
	(*UpdateV1Response)(nil),             // 7: chat_service.UpdateV1Response
	(*ValidateV1Request)(nil),            // 8: chat_service.ValidateV1Request
	(*ValidateV1Response)(nil),           // 9: chat_service.ValidateV1Response
	(*UploadProfileImageV1Request)(nil),  // 10: chat_service.UploadProfileImageV1Request
	(*UploadProfileImageV1Response)(nil), // 11: chat_service.UploadProfileImageV1Response
	(*GetUsersInfoV1Request)(nil),        // 12: chat_service.GetUsersInfoV1Request
	(*GetUsersInfoV1Response)(nil),       // 13: chat_service.GetUsersInfoV1Response
	(*UserInfo)(nil),                     // 14: chat_service.UserInfo
	(*Session)(nil),                      // 15: chat_service.Session
}
var file_user_service_user_service_proto_depIdxs = []int32{
	15, // 0: chat_service.SignUpV1Response.session:type_name -> chat_service.Session
	15, // 1: chat_service.LogInV1Response.session:type_name -> chat_service.Session
	15, // 2: chat_service.LogOutV1Response.session:type_name -> chat_service.Session
	15, // 3: chat_service.UpdateV1Request.session:type_name -> chat_service.Session
	15, // 4: chat_service.ValidateV1Request.session:type_name -> chat_service.Session
	14, // 5: chat_service.ValidateV1Response.info:type_name -> chat_service.UserInfo
	15, // 6: chat_service.UploadProfileImageV1Request.session:type_name -> chat_service.Session
	14, // 7: chat_service.GetUsersInfoV1Response.info:type_name -> chat_service.UserInfo
	0,  // 8: chat_service.UserService.SignUpV1:input_type -> chat_service.SignUpV1Request
	2,  // 9: chat_service.UserService.LogInV1:input_type -> chat_service.LogInV1Request
	4,  // 10: chat_service.UserService.LogOutV1:input_type -> chat_service.LogOutV1Request
	6,  // 11: chat_service.UserService.UpdateV1:input_type -> chat_service.UpdateV1Request
	8,  // 12: chat_service.UserService.ValidateV1:input_type -> chat_service.ValidateV1Request
	10, // 13: chat_service.UserService.UploadProfileImageV1:input_type -> chat_service.UploadProfileImageV1Request
	12, // 14: chat_service.UserService.GetUsersInfoV1:input_type -> chat_service.GetUsersInfoV1Request
	1,  // 15: chat_service.UserService.SignUpV1:output_type -> chat_service.SignUpV1Response
	3,  // 16: chat_service.UserService.LogInV1:output_type -> chat_service.LogInV1Response
	5,  // 17: chat_service.UserService.LogOutV1:output_type -> chat_service.LogOutV1Response
	7,  // 18: chat_service.UserService.UpdateV1:output_type -> chat_service.UpdateV1Response
	9,  // 19: chat_service.UserService.ValidateV1:output_type -> chat_service.ValidateV1Response
	11, // 20: chat_service.UserService.UploadProfileImageV1:output_type -> chat_service.UploadProfileImageV1Response
	13, // 21: chat_service.UserService.GetUsersInfoV1:output_type -> chat_service.GetUsersInfoV1Response
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_user_service_user_service_proto_init() }
func file_user_service_user_service_proto_init() {
	if File_user_service_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_user_service_proto_rawDesc), len(file_user_service_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_user_service_proto_depIdxs,
		MessageInfos:      file_user_service_user_service_proto_msgTypes,
	}.Build()
	File_user_service_user_service_proto = out.File
	file_user_service_user_service_proto_goTypes = nil
	file_user_service_user_service_proto_depIdxs = nil
}
