name: chattery-reverse-proxy

services:
  reverse-proxy:
    image: caddy:2.10-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend_private

volumes:
  caddy_data:
  caddy_config:

networks:
  backend_private:
    name: chattery-backend-private
    external: true
