// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_dm/service.go -package=mock_dm
//

// Package mock_dm is a generated GoMock package.
package mock_dm

import (
	domain "chattery/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockdb is a mock of db interface.
type Mockdb struct {
	ctrl     *gomock.Controller
	recorder *MockdbMockRecorder
}

// MockdbMockRecorder is the mock recorder for Mockdb.
type MockdbMockRecorder struct {
	mock *Mockdb
}

// NewMockdb creates a new mock instance.
func NewMockdb(ctrl *gomock.Controller) *Mockdb {
	mock := &Mockdb{ctrl: ctrl}
	mock.recorder = &MockdbMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdb) EXPECT() *MockdbMockRecorder {
	return m.recorder
}

// CreateDM mocks base method.
func (m *Mockdb) CreateDM(ctx context.Context) (domain.DMID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDM", ctx)
	ret0, _ := ret[0].(domain.DMID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDM indicates an expected call of CreateDM.
func (mr *MockdbMockRecorder) CreateDM(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDM", reflect.TypeOf((*Mockdb)(nil).CreateDM), ctx)
}

// CreateDMMessage mocks base method.
func (m *Mockdb) CreateDMMessage(ctx context.Context, message *domain.DMMessage) (domain.DMMessageID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDMMessage", ctx, message)
	ret0, _ := ret[0].(domain.DMMessageID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDMMessage indicates an expected call of CreateDMMessage.
func (mr *MockdbMockRecorder) CreateDMMessage(ctx, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDMMessage", reflect.TypeOf((*Mockdb)(nil).CreateDMMessage), ctx, message)
}

// CreateDMParticipant mocks base method.
func (m *Mockdb) CreateDMParticipant(ctx context.Context, dmID domain.DMID, userID domain.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDMParticipant", ctx, dmID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDMParticipant indicates an expected call of CreateDMParticipant.
func (mr *MockdbMockRecorder) CreateDMParticipant(ctx, dmID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDMParticipant", reflect.TypeOf((*Mockdb)(nil).CreateDMParticipant), ctx, dmID, userID)
}

// FirstPageOfDMMessages mocks base method.
func (m *Mockdb) FirstPageOfDMMessages(ctx context.Context, cursor *domain.DMCursor) ([]*domain.DMMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FirstPageOfDMMessages", ctx, cursor)
	ret0, _ := ret[0].([]*domain.DMMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FirstPageOfDMMessages indicates an expected call of FirstPageOfDMMessages.
func (mr *MockdbMockRecorder) FirstPageOfDMMessages(ctx, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FirstPageOfDMMessages", reflect.TypeOf((*Mockdb)(nil).FirstPageOfDMMessages), ctx, cursor)
}

// GetDMBetweenUsers mocks base method.
func (m *Mockdb) GetDMBetweenUsers(ctx context.Context, userID1, userID2 domain.UserID) (*domain.DM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDMBetweenUsers", ctx, userID1, userID2)
	ret0, _ := ret[0].(*domain.DM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDMBetweenUsers indicates an expected call of GetDMBetweenUsers.
func (mr *MockdbMockRecorder) GetDMBetweenUsers(ctx, userID1, userID2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDMBetweenUsers", reflect.TypeOf((*Mockdb)(nil).GetDMBetweenUsers), ctx, userID1, userID2)
}

// GetDMMessage mocks base method.
func (m *Mockdb) GetDMMessage(ctx context.Context, dmID domain.DMID, messageID domain.DMMessageID) (*domain.DMMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDMMessage", ctx, dmID, messageID)
	ret0, _ := ret[0].(*domain.DMMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDMMessage indicates an expected call of GetDMMessage.
func (mr *MockdbMockRecorder) GetDMMessage(ctx, dmID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDMMessage", reflect.TypeOf((*Mockdb)(nil).GetDMMessage), ctx, dmID, messageID)
}

// GetDMParticipant mocks base method.
func (m *Mockdb) GetDMParticipant(ctx context.Context, dmID domain.DMID, userID domain.UserID) (*domain.DMParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDMParticipant", ctx, dmID, userID)
	ret0, _ := ret[0].(*domain.DMParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDMParticipant indicates an expected call of GetDMParticipant.
func (mr *MockdbMockRecorder) GetDMParticipant(ctx, dmID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDMParticipant", reflect.TypeOf((*Mockdb)(nil).GetDMParticipant), ctx, dmID, userID)
}

// GetDMParticipants mocks base method.
func (m *Mockdb) GetDMParticipants(ctx context.Context, dmID domain.DMID) ([]domain.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDMParticipants", ctx, dmID)
	ret0, _ := ret[0].([]domain.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDMParticipants indicates an expected call of GetDMParticipants.
func (mr *MockdbMockRecorder) GetDMParticipants(ctx, dmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDMParticipants", reflect.TypeOf((*Mockdb)(nil).GetDMParticipants), ctx, dmID)
}

// GetUserDMParticipantIDs mocks base method.
func (m *Mockdb) GetUserDMParticipantIDs(ctx context.Context, userID domain.UserID) ([]domain.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserDMParticipantIDs", ctx, userID)
	ret0, _ := ret[0].([]domain.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserDMParticipantIDs indicates an expected call of GetUserDMParticipantIDs.
func (mr *MockdbMockRecorder) GetUserDMParticipantIDs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserDMParticipantIDs", reflect.TypeOf((*Mockdb)(nil).GetUserDMParticipantIDs), ctx, userID)
}

// NextPagesOfDMMessages mocks base method.
func (m *Mockdb) NextPagesOfDMMessages(ctx context.Context, cursor *domain.DMCursor) ([]*domain.DMMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextPagesOfDMMessages", ctx, cursor)
	ret0, _ := ret[0].([]*domain.DMMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextPagesOfDMMessages indicates an expected call of NextPagesOfDMMessages.
func (mr *MockdbMockRecorder) NextPagesOfDMMessages(ctx, cursor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPagesOfDMMessages", reflect.TypeOf((*Mockdb)(nil).NextPagesOfDMMessages), ctx, cursor)
}

// SetDMLastReadMessage mocks base method.
func (m *Mockdb) SetDMLastReadMessage(ctx context.Context, dmID domain.DMID, userID domain.UserID, messageID domain.DMMessageID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDMLastReadMessage", ctx, dmID, userID, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDMLastReadMessage indicates an expected call of SetDMLastReadMessage.
func (mr *MockdbMockRecorder) SetDMLastReadMessage(ctx, dmID, userID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDMLastReadMessage", reflect.TypeOf((*Mockdb)(nil).SetDMLastReadMessage), ctx, dmID, userID, messageID)
}

// SetLastMessageInDM mocks base method.
func (m *Mockdb) SetLastMessageInDM(ctx context.Context, dmID domain.DMID, messageID domain.DMMessageID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastMessageInDM", ctx, dmID, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastMessageInDM indicates an expected call of SetLastMessageInDM.
func (mr *MockdbMockRecorder) SetLastMessageInDM(ctx, dmID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastMessageInDM", reflect.TypeOf((*Mockdb)(nil).SetLastMessageInDM), ctx, dmID, messageID)
}

// UserDMs mocks base method.
func (m *Mockdb) UserDMs(ctx context.Context, userID domain.UserID) ([]*domain.DM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserDMs", ctx, userID)
	ret0, _ := ret[0].([]*domain.DM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserDMs indicates an expected call of UserDMs.
func (mr *MockdbMockRecorder) UserDMs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserDMs", reflect.TypeOf((*Mockdb)(nil).UserDMs), ctx, userID)
}

// Mockredis is a mock of redis interface.
type Mockredis struct {
	ctrl     *gomock.Controller
	recorder *MockredisMockRecorder
}

// MockredisMockRecorder is the mock recorder for Mockredis.
type MockredisMockRecorder struct {
	mock *Mockredis
}

// NewMockredis creates a new mock instance.
func NewMockredis(ctrl *gomock.Controller) *Mockredis {
	mock := &Mockredis{ctrl: ctrl}
	mock.recorder = &MockredisMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockredis) EXPECT() *MockredisMockRecorder {
	return m.recorder
}

// PublishToUser mocks base method.
func (m *Mockredis) PublishToUser(ctx context.Context, userID domain.UserID, event []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishToUser", ctx, userID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishToUser indicates an expected call of PublishToUser.
func (mr *MockredisMockRecorder) PublishToUser(ctx, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishToUser", reflect.TypeOf((*Mockredis)(nil).PublishToUser), ctx, userID, event)
}

// MockuserCache is a mock of userCache interface.
type MockuserCache struct {
	ctrl     *gomock.Controller
	recorder *MockuserCacheMockRecorder
}

// MockuserCacheMockRecorder is the mock recorder for MockuserCache.
type MockuserCacheMockRecorder struct {
	mock *MockuserCache
}

// NewMockuserCache creates a new mock instance.
func NewMockuserCache(ctrl *gomock.Controller) *MockuserCache {
	mock := &MockuserCache{ctrl: ctrl}
	mock.recorder = &MockuserCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserCache) EXPECT() *MockuserCacheMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockuserCache) GetByID(userID domain.UserID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserCacheMockRecorder) GetByID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserCache)(nil).GetByID), userID)
}

// List mocks base method.
func (m *MockuserCache) List() []*domain.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*domain.User)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockuserCacheMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockuserCache)(nil).List))
}

// MockdmCache is a mock of dmCache interface.
type MockdmCache struct {
	ctrl     *gomock.Controller
	recorder *MockdmCacheMockRecorder
}

// MockdmCacheMockRecorder is the mock recorder for MockdmCache.
type MockdmCacheMockRecorder struct {
	mock *MockdmCache
}

// NewMockdmCache creates a new mock instance.
func NewMockdmCache(ctrl *gomock.Controller) *MockdmCache {
	mock := &MockdmCache{ctrl: ctrl}
	mock.recorder = &MockdmCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdmCache) EXPECT() *MockdmCacheMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockdmCache) GetByID(dmID domain.DMID) (*domain.DM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", dmID)
	ret0, _ := ret[0].(*domain.DM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockdmCacheMockRecorder) GetByID(dmID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockdmCache)(nil).GetByID), dmID)
}

// List mocks base method.
func (m *MockdmCache) List() []*domain.DM {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]*domain.DM)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockdmCacheMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockdmCache)(nil).List))
}

// MocktxManager is a mock of txManager interface.
type MocktxManager struct {
	ctrl     *gomock.Controller
	recorder *MocktxManagerMockRecorder
}

// MocktxManagerMockRecorder is the mock recorder for MocktxManager.
type MocktxManagerMockRecorder struct {
	mock *MocktxManager
}

// NewMocktxManager creates a new mock instance.
func NewMocktxManager(ctrl *gomock.Controller) *MocktxManager {
	mock := &MocktxManager{ctrl: ctrl}
	mock.recorder = &MocktxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktxManager) EXPECT() *MocktxManagerMockRecorder {
	return m.recorder
}

// InTransaction mocks base method.
func (m *MocktxManager) InTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTransaction indicates an expected call of InTransaction.
func (mr *MocktxManagerMockRecorder) InTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTransaction", reflect.TypeOf((*MocktxManager)(nil).InTransaction), ctx, fn)
}
