// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package postgres

import (
	"context"
	"time"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO chat_participants(chat_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddParticipantParams struct {
	ChatID int64
	UserID int64
	Role   string
}

// AddParticipant
//
//	INSERT INTO chat_participants(chat_id, user_id, role)
//	VALUES ($1, $2, $3)
func (q *Queries) AddParticipant(ctx context.Context, arg *AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.ChatID, arg.UserID, arg.Role)
	return err
}

const chats = `-- name: Chats :many
SELECT id, type, name, created_at, updated_at FROM chats
`

// Chats
//
//	SELECT id, type, name, created_at, updated_at FROM chats
func (q *Queries) Chats(ctx context.Context) ([]*Chat, error) {
	rows, err := q.db.Query(ctx, chats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats(type, name)
VALUES ($1, $2)
RETURNING id
`

type CreateChatParams struct {
	Type string
	Name string
}

// CreateChat
//
//	INSERT INTO chats(type, name)
//	VALUES ($1, $2)
//	RETURNING id
func (q *Queries) CreateChat(ctx context.Context, arg *CreateChatParams) (int64, error) {
	row := q.db.QueryRow(ctx, createChat, arg.Type, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO chat_messages(chat_id, user_id, text)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateMessageParams struct {
	ChatID int64
	UserID int64
	Text   string
}

// CreateMessage
//
//	INSERT INTO chat_messages(chat_id, user_id, text)
//	VALUES ($1, $2, $3)
//	RETURNING id
func (q *Queries) CreateMessage(ctx context.Context, arg *CreateMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChatID, arg.UserID, arg.Text)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats
WHERE id=$1
`

// DeleteChat
//
//	DELETE FROM chats
//	WHERE id=$1
func (q *Queries) DeleteChat(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteChat, id)
	return err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM chat_participants
WHERE chat_id=$1 AND user_id=$2
`

type DeleteParticipantParams struct {
	ChatID int64
	UserID int64
}

// DeleteParticipant
//
//	DELETE FROM chat_participants
//	WHERE chat_id=$1 AND user_id=$2
func (q *Queries) DeleteParticipant(ctx context.Context, arg *DeleteParticipantParams) error {
	_, err := q.db.Exec(ctx, deleteParticipant, arg.ChatID, arg.UserID)
	return err
}

const firstPageOfMessages = `-- name: FirstPageOfMessages :many
SELECT id, chat_id, user_id, text, created_at FROM chat_messages
WHERE chat_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type FirstPageOfMessagesParams struct {
	ChatID int64
	Limit  int32
}

// FirstPageOfMessages
//
//	SELECT id, chat_id, user_id, text, created_at FROM chat_messages
//	WHERE chat_id = $1
//	ORDER BY created_at DESC, id DESC
//	LIMIT $2
func (q *Queries) FirstPageOfMessages(ctx context.Context, arg *FirstPageOfMessagesParams) ([]*ChatMessage, error) {
	rows, err := q.db.Query(ctx, firstPageOfMessages, arg.ChatID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPagesOfMessages = `-- name: NextPagesOfMessages :many
SELECT id, chat_id, user_id, text, created_at FROM chat_messages
WHERE chat_id = $1 AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type NextPagesOfMessagesParams struct {
	ChatID    int64
	CreatedAt time.Time
	ID        int64
	Limit     int32
}

// NextPagesOfMessages
//
//	SELECT id, chat_id, user_id, text, created_at FROM chat_messages
//	WHERE chat_id = $1 AND (created_at < $2 OR (created_at = $2 AND id < $3))
//	ORDER BY created_at DESC, id DESC
//	LIMIT $4
func (q *Queries) NextPagesOfMessages(ctx context.Context, arg *NextPagesOfMessagesParams) ([]*ChatMessage, error) {
	rows, err := q.db.Query(ctx, nextPagesOfMessages,
		arg.ChatID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const participantsForChat = `-- name: ParticipantsForChat :many
SELECT chat_id, user_id, role, created_at FROM chat_participants
WHERE chat_id = $1
`

// ParticipantsForChat
//
//	SELECT chat_id, user_id, role, created_at FROM chat_participants
//	WHERE chat_id = $1
func (q *Queries) ParticipantsForChat(ctx context.Context, chatID int64) ([]*ChatParticipant, error) {
	rows, err := q.db.Query(ctx, participantsForChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ChatParticipant
	for rows.Next() {
		var i ChatParticipant
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userChatPreviewByType = `-- name: UserChatPreviewByType :many
SELECT
    c.id,
    c.type,
    c.name,
    c.created_at,
    c.updated_at,
    (m.id IS NOT NULL)::boolean           AS has_last_message,
    COALESCE(m.id, 0)                     AS last_message_id,
    COALESCE(m.user_id, 0)                AS last_message_user_id,
    COALESCE(m.text, '')                  AS last_message_text,
    COALESCE(m.created_at, TIMESTAMP 'epoch') AS last_message_created_at
FROM chats c
JOIN chat_participants cp
    ON cp.chat_id = c.id AND cp.user_id = $1
LEFT JOIN LATERAL (
    SELECT id, user_id, text, created_at
    FROM chat_messages
    WHERE chat_id = c.id
    ORDER BY created_at DESC, id DESC
    LIMIT 1
) m ON true
WHERE c.type = $2
ORDER BY m.created_at DESC NULLS LAST, c.updated_at DESC, c.id DESC
`

type UserChatPreviewByTypeParams struct {
	UserID int64
	Type   string
}

type UserChatPreviewByTypeRow struct {
	ID                   int64
	Type                 string
	Name                 string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	HasLastMessage       bool
	LastMessageID        int64
	LastMessageUserID    int64
	LastMessageText      string
	LastMessageCreatedAt time.Time
}

// UserChatPreviewByType
//
//	SELECT
//	    c.id,
//	    c.type,
//	    c.name,
//	    c.created_at,
//	    c.updated_at,
//	    (m.id IS NOT NULL)::boolean           AS has_last_message,
//	    COALESCE(m.id, 0)                     AS last_message_id,
//	    COALESCE(m.user_id, 0)                AS last_message_user_id,
//	    COALESCE(m.text, '')                  AS last_message_text,
//	    COALESCE(m.created_at, TIMESTAMP 'epoch') AS last_message_created_at
//	FROM chats c
//	JOIN chat_participants cp
//	    ON cp.chat_id = c.id AND cp.user_id = $1
//	LEFT JOIN LATERAL (
//	    SELECT id, user_id, text, created_at
//	    FROM chat_messages
//	    WHERE chat_id = c.id
//	    ORDER BY created_at DESC, id DESC
//	    LIMIT 1
//	) m ON true
//	WHERE c.type = $2
//	ORDER BY m.created_at DESC NULLS LAST, c.updated_at DESC, c.id DESC
func (q *Queries) UserChatPreviewByType(ctx context.Context, arg *UserChatPreviewByTypeParams) ([]*UserChatPreviewByTypeRow, error) {
	rows, err := q.db.Query(ctx, userChatPreviewByType, arg.UserID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserChatPreviewByTypeRow
	for rows.Next() {
		var i UserChatPreviewByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasLastMessage,
			&i.LastMessageID,
			&i.LastMessageUserID,
			&i.LastMessageText,
			&i.LastMessageCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userChats = `-- name: UserChats :many
SELECT id, type, name, created_at, updated_at FROM chats
WHERE chats.id in (
    SELECT chat_id FROM chat_participants
    WHERE user_id=$1
)
`

// UserChats
//
//	SELECT id, type, name, created_at, updated_at FROM chats
//	WHERE chats.id in (
//	    SELECT chat_id FROM chat_participants
//	    WHERE user_id=$1
//	)
func (q *Queries) UserChats(ctx context.Context, userID int64) ([]*Chat, error) {
	rows, err := q.db.Query(ctx, userChats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
