// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dm.sql

package postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDM = `-- name: CreateDM :one
INSERT INTO dms(last_message_id)
VALUES (0)
RETURNING id
`

// CreateDM
//
//	INSERT INTO dms(last_message_id)
//	VALUES (0)
//	RETURNING id
func (q *Queries) CreateDM(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, createDM)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createDMMessage = `-- name: CreateDMMessage :one
INSERT INTO dm_messages(dm_id, user_id, text)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateDMMessageParams struct {
	DmID   int64
	UserID int64
	Text   string
}

// CreateDMMessage
//
//	INSERT INTO dm_messages(dm_id, user_id, text)
//	VALUES ($1, $2, $3)
//	RETURNING id
func (q *Queries) CreateDMMessage(ctx context.Context, arg *CreateDMMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createDMMessage, arg.DmID, arg.UserID, arg.Text)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createDMParticipant = `-- name: CreateDMParticipant :exec
INSERT INTO dm_participants(dm_id, user_id)
VALUES ($1, $2)
`

type CreateDMParticipantParams struct {
	DmID   int64
	UserID int64
}

// CreateDMParticipant
//
//	INSERT INTO dm_participants(dm_id, user_id)
//	VALUES ($1, $2)
func (q *Queries) CreateDMParticipant(ctx context.Context, arg *CreateDMParticipantParams) error {
	_, err := q.db.Exec(ctx, createDMParticipant, arg.DmID, arg.UserID)
	return err
}

const firstPageOfDMMessages = `-- name: FirstPageOfDMMessages :many
SELECT id, dm_id, user_id, text, created_at, updated_at FROM dm_messages
WHERE dm_id = $1
ORDER BY created_at ASC, id ASC
LIMIT $2
`

type FirstPageOfDMMessagesParams struct {
	DmID  int64
	Limit int32
}

// FirstPageOfDMMessages
//
//	SELECT id, dm_id, user_id, text, created_at, updated_at FROM dm_messages
//	WHERE dm_id = $1
//	ORDER BY created_at ASC, id ASC
//	LIMIT $2
func (q *Queries) FirstPageOfDMMessages(ctx context.Context, arg *FirstPageOfDMMessagesParams) ([]*DmMessage, error) {
	rows, err := q.db.Query(ctx, firstPageOfDMMessages, arg.DmID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DmMessage
	for rows.Next() {
		var i DmMessage
		if err := rows.Scan(
			&i.ID,
			&i.DmID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDMBetweenUsers = `-- name: GetDMBetweenUsers :one
SELECT d.id FROM dm_participants p1
JOIN dm_participants p2 ON p1.dm_id = p2.dm_id
JOIN dms d ON d.id = p1.dm_id
WHERE p1.user_id = $1 AND p2.user_id = $2
LIMIT 1
`

type GetDMBetweenUsersParams struct {
	UserID   int64
	UserID_2 int64
}

// GetDMBetweenUsers
//
//	SELECT d.id FROM dm_participants p1
//	JOIN dm_participants p2 ON p1.dm_id = p2.dm_id
//	JOIN dms d ON d.id = p1.dm_id
//	WHERE p1.user_id = $1 AND p2.user_id = $2
//	LIMIT 1
func (q *Queries) GetDMBetweenUsers(ctx context.Context, arg *GetDMBetweenUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDMBetweenUsers, arg.UserID, arg.UserID_2)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getDMParticipant = `-- name: GetDMParticipant :one
SELECT dm_id, user_id, last_read_message_id, created_at, updated_at FROM dm_participants
WHERE dm_id = $1 AND user_id = $2
`

type GetDMParticipantParams struct {
	DmID   int64
	UserID int64
}

// GetDMParticipant
//
//	SELECT dm_id, user_id, last_read_message_id, created_at, updated_at FROM dm_participants
//	WHERE dm_id = $1 AND user_id = $2
func (q *Queries) GetDMParticipant(ctx context.Context, arg *GetDMParticipantParams) (*DmParticipant, error) {
	row := q.db.QueryRow(ctx, getDMParticipant, arg.DmID, arg.UserID)
	var i DmParticipant
	err := row.Scan(
		&i.DmID,
		&i.UserID,
		&i.LastReadMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getDMParticipants = `-- name: GetDMParticipants :many
SELECT user_id FROM dm_participants
WHERE dm_id = $1
`

// GetDMParticipants
//
//	SELECT user_id FROM dm_participants
//	WHERE dm_id = $1
func (q *Queries) GetDMParticipants(ctx context.Context, dmID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getDMParticipants, dmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPagesOfDMMessages = `-- name: NextPagesOfDMMessages :many
SELECT id, dm_id, user_id, text, created_at, updated_at FROM dm_messages
WHERE dm_id = $1 AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at ASC, id ASC
LIMIT $4
`

type NextPagesOfDMMessagesParams struct {
	DmID      int64
	CreatedAt time.Time
	ID        int64
	Limit     int32
}

// NextPagesOfDMMessages
//
//	SELECT id, dm_id, user_id, text, created_at, updated_at FROM dm_messages
//	WHERE dm_id = $1 AND (created_at < $2 OR (created_at = $2 AND id < $3))
//	ORDER BY created_at ASC, id ASC
//	LIMIT $4
func (q *Queries) NextPagesOfDMMessages(ctx context.Context, arg *NextPagesOfDMMessagesParams) ([]*DmMessage, error) {
	rows, err := q.db.Query(ctx, nextPagesOfDMMessages,
		arg.DmID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DmMessage
	for rows.Next() {
		var i DmMessage
		if err := rows.Scan(
			&i.ID,
			&i.DmID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDMLastReadMessage = `-- name: SetDMLastReadMessage :exec
UPDATE dm_participants
SET last_read_message_id=$3,
    updated_at=now()
WHERE dm_id=$1 AND user_id=$2
`

type SetDMLastReadMessageParams struct {
	DmID              int64
	UserID            int64
	LastReadMessageID int64
}

// SetDMLastReadMessage
//
//	UPDATE dm_participants
//	SET last_read_message_id=$3,
//	    updated_at=now()
//	WHERE dm_id=$1 AND user_id=$2
func (q *Queries) SetDMLastReadMessage(ctx context.Context, arg *SetDMLastReadMessageParams) error {
	_, err := q.db.Exec(ctx, setDMLastReadMessage, arg.DmID, arg.UserID, arg.LastReadMessageID)
	return err
}

const setLastMessageInDM = `-- name: SetLastMessageInDM :exec
UPDATE dms
SET last_message_id=$2,
    updated_at=now()
WHERE id = $1
`

type SetLastMessageInDMParams struct {
	ID            int64
	LastMessageID int64
}

// SetLastMessageInDM
//
//	UPDATE dms
//	SET last_message_id=$2,
//	    updated_at=now()
//	WHERE id = $1
func (q *Queries) SetLastMessageInDM(ctx context.Context, arg *SetLastMessageInDMParams) error {
	_, err := q.db.Exec(ctx, setLastMessageInDM, arg.ID, arg.LastMessageID)
	return err
}

const userDMs = `-- name: UserDMs :many
SELECT
    d.id AS dm_id,
    d.updated_at AS last_activity_at,
    p.last_read_message_id,
    lm.id AS last_message_id,
    lm.user_id AS last_message_sender_id,
    lm.text AS last_message_text,
    lm.created_at AS last_message_created_at,
    p2.user_id AS other_participant_id
FROM dm_participants p
JOIN dms d ON d.id = p.dm_id
LEFT JOIN dm_messages lm ON lm.id = d.last_message_id
JOIN dm_participants p2 ON p2.dm_id = d.id AND p2.user_id != $1
WHERE p.user_id = $1
`

type UserDMsRow struct {
	DmID                 int64
	LastActivityAt       time.Time
	LastReadMessageID    int64
	LastMessageID        pgtype.Int8
	LastMessageSenderID  pgtype.Int8
	LastMessageText      pgtype.Text
	LastMessageCreatedAt pgtype.Timestamp
	OtherParticipantID   int64
}

// UserDMs
//
//	SELECT
//	    d.id AS dm_id,
//	    d.updated_at AS last_activity_at,
//	    p.last_read_message_id,
//	    lm.id AS last_message_id,
//	    lm.user_id AS last_message_sender_id,
//	    lm.text AS last_message_text,
//	    lm.created_at AS last_message_created_at,
//	    p2.user_id AS other_participant_id
//	FROM dm_participants p
//	JOIN dms d ON d.id = p.dm_id
//	LEFT JOIN dm_messages lm ON lm.id = d.last_message_id
//	JOIN dm_participants p2 ON p2.dm_id = d.id AND p2.user_id != $1
//	WHERE p.user_id = $1
func (q *Queries) UserDMs(ctx context.Context, userID int64) ([]*UserDMsRow, error) {
	rows, err := q.db.Query(ctx, userDMs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserDMsRow
	for rows.Next() {
		var i UserDMsRow
		if err := rows.Scan(
			&i.DmID,
			&i.LastActivityAt,
			&i.LastReadMessageID,
			&i.LastMessageID,
			&i.LastMessageSenderID,
			&i.LastMessageText,
			&i.LastMessageCreatedAt,
			&i.OtherParticipantID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
