// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"
)

type Chat struct {
	ID        int64
	Type      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ChatMessage struct {
	ID        int64
	ChatID    int64
	Username  string
	Text      string
	CreatedAt time.Time
}

type ChatParticipant struct {
	ChatID    int64
	Username  string
	CreatedAt time.Time
}

type User struct {
	Username  string
	Login     string
	Password  []byte
	AvatarID  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
