// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"
)

type Dm struct {
	ID            int64
	LastMessageID int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type DmMessage struct {
	ID        int64
	DmID      int64
	UserID    int64
	Text      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type DmParticipant struct {
	DmID              int64
	UserID            int64
	LastReadMessageID int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Server struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ServerParticipant struct {
	ServerID  int64
	UserID    int64
	Role      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Topic struct {
	ID        int64
	ServerID  int64
	Name      string
	Type      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TopicMessage struct {
	ID        int64
	TopicID   int64
	UserID    int64
	Text      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        int64
	Username  string
	Login     string
	Password  []byte
	AvatarID  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
