// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: server.sql

package postgres

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO topic_messages(topic_id, user_id, text)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateMessageParams struct {
	TopicID int64
	UserID  int64
	Text    string
}

// CreateMessage
//
//	INSERT INTO topic_messages(topic_id, user_id, text)
//	VALUES ($1, $2, $3)
//	RETURNING id
func (q *Queries) CreateMessage(ctx context.Context, arg *CreateMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.TopicID, arg.UserID, arg.Text)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createServer = `-- name: CreateServer :one
INSERT INTO servers(name)
VALUES ($1)
RETURNING id
`

// CreateServer
//
//	INSERT INTO servers(name)
//	VALUES ($1)
//	RETURNING id
func (q *Queries) CreateServer(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, createServer, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createServerParticipant = `-- name: CreateServerParticipant :exec
INSERT INTO server_participants (server_id, user_id, role)
VALUES ($1, $2, $3)
`

type CreateServerParticipantParams struct {
	ServerID int64
	UserID   int64
	Role     string
}

// CreateServerParticipant
//
//	INSERT INTO server_participants (server_id, user_id, role)
//	VALUES ($1, $2, $3)
func (q *Queries) CreateServerParticipant(ctx context.Context, arg *CreateServerParticipantParams) error {
	_, err := q.db.Exec(ctx, createServerParticipant, arg.ServerID, arg.UserID, arg.Role)
	return err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (server_id, name, type)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateTopicParams struct {
	ServerID int64
	Name     string
	Type     string
}

// CreateTopic
//
//	INSERT INTO topics (server_id, name, type)
//	VALUES ($1, $2, $3)
//	RETURNING id
func (q *Queries) CreateTopic(ctx context.Context, arg *CreateTopicParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTopic, arg.ServerID, arg.Name, arg.Type)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteMessagesByServerID = `-- name: DeleteMessagesByServerID :exec
DELETE FROM topic_messages
WHERE topic_id IN (SELECT id FROM topics WHERE server_id = $1)
`

// DeleteMessagesByServerID
//
//	DELETE FROM topic_messages
//	WHERE topic_id IN (SELECT id FROM topics WHERE server_id = $1)
func (q *Queries) DeleteMessagesByServerID(ctx context.Context, serverID int64) error {
	_, err := q.db.Exec(ctx, deleteMessagesByServerID, serverID)
	return err
}

const deleteServerByServerID = `-- name: DeleteServerByServerID :exec
DELETE FROM servers
WHERE id = $1
`

// DeleteServerByServerID
//
//	DELETE FROM servers
//	WHERE id = $1
func (q *Queries) DeleteServerByServerID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteServerByServerID, id)
	return err
}

const deleteServerParticipant = `-- name: DeleteServerParticipant :exec
DELETE FROM server_participants
WHERE server_id = $1 AND user_id = $2
`

type DeleteServerParticipantParams struct {
	ServerID int64
	UserID   int64
}

// DeleteServerParticipant
//
//	DELETE FROM server_participants
//	WHERE server_id = $1 AND user_id = $2
func (q *Queries) DeleteServerParticipant(ctx context.Context, arg *DeleteServerParticipantParams) error {
	_, err := q.db.Exec(ctx, deleteServerParticipant, arg.ServerID, arg.UserID)
	return err
}

const deleteServerParticipantsByServerID = `-- name: DeleteServerParticipantsByServerID :exec
DELETE FROM server_participants
WHERE server_id = $1
`

// DeleteServerParticipantsByServerID
//
//	DELETE FROM server_participants
//	WHERE server_id = $1
func (q *Queries) DeleteServerParticipantsByServerID(ctx context.Context, serverID int64) error {
	_, err := q.db.Exec(ctx, deleteServerParticipantsByServerID, serverID)
	return err
}

const deleteTopic = `-- name: DeleteTopic :exec
DELETE FROM topics
WHERE id = $1
`

// DeleteTopic
//
//	DELETE FROM topics
//	WHERE id = $1
func (q *Queries) DeleteTopic(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTopic, id)
	return err
}

const deleteTopicsByServerID = `-- name: DeleteTopicsByServerID :exec
DELETE FROM topics
WHERE server_id = $1
`

// DeleteTopicsByServerID
//
//	DELETE FROM topics
//	WHERE server_id = $1
func (q *Queries) DeleteTopicsByServerID(ctx context.Context, serverID int64) error {
	_, err := q.db.Exec(ctx, deleteTopicsByServerID, serverID)
	return err
}

const firstPageOfTopicMessages = `-- name: FirstPageOfTopicMessages :many
SELECT id, topic_id, user_id, text, created_at, updated_at FROM topic_messages
WHERE topic_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type FirstPageOfTopicMessagesParams struct {
	TopicID int64
	Limit   int32
}

// FirstPageOfTopicMessages
//
//	SELECT id, topic_id, user_id, text, created_at, updated_at FROM topic_messages
//	WHERE topic_id = $1
//	ORDER BY created_at DESC, id DESC
//	LIMIT $2
func (q *Queries) FirstPageOfTopicMessages(ctx context.Context, arg *FirstPageOfTopicMessagesParams) ([]*TopicMessage, error) {
	rows, err := q.db.Query(ctx, firstPageOfTopicMessages, arg.TopicID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TopicMessage
	for rows.Next() {
		var i TopicMessage
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServer = `-- name: GetServer :many
SELECT
    s.id AS id,
    s.name AS name,
    t.id AS topic_id,
    t.name AS topic_name,
    t.type AS topic_type,
    t.created_at AS topic_created_at
FROM servers s
LEFT JOIN topics t ON t.server_id = s.id
WHERE s.id=$1
`

type GetServerRow struct {
	ID             int64
	Name           string
	TopicID        pgtype.Int8
	TopicName      pgtype.Text
	TopicType      pgtype.Text
	TopicCreatedAt pgtype.Timestamp
}

// GetServer
//
//	SELECT
//	    s.id AS id,
//	    s.name AS name,
//	    t.id AS topic_id,
//	    t.name AS topic_name,
//	    t.type AS topic_type,
//	    t.created_at AS topic_created_at
//	FROM servers s
//	LEFT JOIN topics t ON t.server_id = s.id
//	WHERE s.id=$1
func (q *Queries) GetServer(ctx context.Context, id int64) ([]*GetServerRow, error) {
	rows, err := q.db.Query(ctx, getServer, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetServerRow
	for rows.Next() {
		var i GetServerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TopicID,
			&i.TopicName,
			&i.TopicType,
			&i.TopicCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerParticipant = `-- name: GetServerParticipant :one
SELECT server_id, user_id, role, created_at, updated_at FROM server_participants
WHERE server_id = $1 AND user_id = $2
`

type GetServerParticipantParams struct {
	ServerID int64
	UserID   int64
}

// GetServerParticipant
//
//	SELECT server_id, user_id, role, created_at, updated_at FROM server_participants
//	WHERE server_id = $1 AND user_id = $2
func (q *Queries) GetServerParticipant(ctx context.Context, arg *GetServerParticipantParams) (*ServerParticipant, error) {
	row := q.db.QueryRow(ctx, getServerParticipant, arg.ServerID, arg.UserID)
	var i ServerParticipant
	err := row.Scan(
		&i.ServerID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTopic = `-- name: GetTopic :one
SELECT id, server_id, name, type, created_at, updated_at FROM topics
WHERE id=$1
`

// GetTopic
//
//	SELECT id, server_id, name, type, created_at, updated_at FROM topics
//	WHERE id=$1
func (q *Queries) GetTopic(ctx context.Context, id int64) (*Topic, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i Topic
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserServers = `-- name: GetUserServers :many
SELECT
    s.id AS id,
    s.name AS name,
    sp.created_at AS joined_at,
    sp.role AS role,
    t.id AS topic_id,
    t.name AS topic_name,
    t.type AS topic_type,
    t.created_at AS topic_created_at
FROM servers s
JOIN server_participants sp ON sp.server_id = s.id
LEFT JOIN topics t ON t.server_id = s.id
WHERE sp.user_id = $1
`

type GetUserServersRow struct {
	ID             int64
	Name           string
	JoinedAt       time.Time
	Role           string
	TopicID        pgtype.Int8
	TopicName      pgtype.Text
	TopicType      pgtype.Text
	TopicCreatedAt pgtype.Timestamp
}

// GetUserServers
//
//	SELECT
//	    s.id AS id,
//	    s.name AS name,
//	    sp.created_at AS joined_at,
//	    sp.role AS role,
//	    t.id AS topic_id,
//	    t.name AS topic_name,
//	    t.type AS topic_type,
//	    t.created_at AS topic_created_at
//	FROM servers s
//	JOIN server_participants sp ON sp.server_id = s.id
//	LEFT JOIN topics t ON t.server_id = s.id
//	WHERE sp.user_id = $1
func (q *Queries) GetUserServers(ctx context.Context, userID int64) ([]*GetUserServersRow, error) {
	rows, err := q.db.Query(ctx, getUserServers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetUserServersRow
	for rows.Next() {
		var i GetUserServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.JoinedAt,
			&i.Role,
			&i.TopicID,
			&i.TopicName,
			&i.TopicType,
			&i.TopicCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextPagesOfTopicMessages = `-- name: NextPagesOfTopicMessages :many
SELECT id, topic_id, user_id, text, created_at, updated_at FROM topic_messages
WHERE topic_id = $1 AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type NextPagesOfTopicMessagesParams struct {
	TopicID   int64
	CreatedAt time.Time
	ID        int64
	Limit     int32
}

// NextPagesOfTopicMessages
//
//	SELECT id, topic_id, user_id, text, created_at, updated_at FROM topic_messages
//	WHERE topic_id = $1 AND (created_at < $2 OR (created_at = $2 AND id < $3))
//	ORDER BY created_at DESC, id DESC
//	LIMIT $4
func (q *Queries) NextPagesOfTopicMessages(ctx context.Context, arg *NextPagesOfTopicMessagesParams) ([]*TopicMessage, error) {
	rows, err := q.db.Query(ctx, nextPagesOfTopicMessages,
		arg.TopicID,
		arg.CreatedAt,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TopicMessage
	for rows.Next() {
		var i TopicMessage
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.UserID,
			&i.Text,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServer = `-- name: UpdateServer :exec
UPDATE servers
SET name=$2,
    updated_at=now()
WHERE id=$1
`

type UpdateServerParams struct {
	ID   int64
	Name string
}

// UpdateServer
//
//	UPDATE servers
//	SET name=$2,
//	    updated_at=now()
//	WHERE id=$1
func (q *Queries) UpdateServer(ctx context.Context, arg *UpdateServerParams) error {
	_, err := q.db.Exec(ctx, updateServer, arg.ID, arg.Name)
	return err
}

const updateTopic = `-- name: UpdateTopic :exec
UPDATE topics
SET
    name = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateTopicParams struct {
	ID   int64
	Name string
}

// UpdateTopic
//
//	UPDATE topics
//	SET
//	    name = $2,
//	    updated_at = NOW()
//	WHERE id = $1
func (q *Queries) UpdateTopic(ctx context.Context, arg *UpdateTopicParams) error {
	_, err := q.db.Exec(ctx, updateTopic, arg.ID, arg.Name)
	return err
}
