// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package postgres

import (
	"context"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users(login, password, username)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	Login    string
	Password []byte
	Username string
}

// CreateUser
//
//	INSERT INTO users(login, password, username)
//	VALUES ($1, $2, $3)
func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Login, arg.Password, arg.Username)
	return err
}

const deleteUserByUsername = `-- name: DeleteUserByUsername :execrows
DELETE FROM users
WHERE username = $1
`

// DeleteUserByUsername
//
//	DELETE FROM users
//	WHERE username = $1
func (q *Queries) DeleteUserByUsername(ctx context.Context, username string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserByUsername, username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = $1,
    login = $2,
    password = $3,
    avatar_id = $4,
    updated_at=now()
WHERE username = $5
`

type UpdateUserParams struct {
	NewUsername string
	NewLogin    string
	NewPassword []byte
	NewAvatarID string
	OldUsername string
}

// UpdateUser
//
//	UPDATE users
//	SET username = $1,
//	    login = $2,
//	    password = $3,
//	    avatar_id = $4,
//	    updated_at=now()
//	WHERE username = $5
func (q *Queries) UpdateUser(ctx context.Context, arg *UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.NewUsername,
		arg.NewLogin,
		arg.NewPassword,
		arg.NewAvatarID,
		arg.OldUsername,
	)
	return err
}

const userByLogin = `-- name: UserByLogin :one
SELECT username, login, password, avatar_id, created_at, updated_at FROM users
WHERE login = $1
`

// UserByLogin
//
//	SELECT username, login, password, avatar_id, created_at, updated_at FROM users
//	WHERE login = $1
func (q *Queries) UserByLogin(ctx context.Context, login string) (*User, error) {
	row := q.db.QueryRow(ctx, userByLogin, login)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Login,
		&i.Password,
		&i.AvatarID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const userByUsername = `-- name: UserByUsername :one
SELECT username, login, password, avatar_id, created_at, updated_at FROM users
WHERE username = $1
`

// UserByUsername
//
//	SELECT username, login, password, avatar_id, created_at, updated_at FROM users
//	WHERE username = $1
func (q *Queries) UserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRow(ctx, userByUsername, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Login,
		&i.Password,
		&i.AvatarID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
