// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: user_service/user_service.proto

package user_servicepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpV1Request) Reset() {
	*x = SignUpV1Request{}
	mi := &file_user_service_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpV1Request) ProtoMessage() {}

func (x *SignUpV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpV1Request.ProtoReflect.Descriptor instead.
func (*SignUpV1Request) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{0}
}

type SignUpV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpV1Response) Reset() {
	*x = SignUpV1Response{}
	mi := &file_user_service_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpV1Response) ProtoMessage() {}

func (x *SignUpV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpV1Response.ProtoReflect.Descriptor instead.
func (*SignUpV1Response) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{1}
}

type LogInV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInV1Request) Reset() {
	*x = LogInV1Request{}
	mi := &file_user_service_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInV1Request) ProtoMessage() {}

func (x *LogInV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInV1Request.ProtoReflect.Descriptor instead.
func (*LogInV1Request) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{2}
}

type LogInV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInV1Response) Reset() {
	*x = LogInV1Response{}
	mi := &file_user_service_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInV1Response) ProtoMessage() {}

func (x *LogInV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInV1Response.ProtoReflect.Descriptor instead.
func (*LogInV1Response) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{3}
}

type LogOutV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogOutV1Request) Reset() {
	*x = LogOutV1Request{}
	mi := &file_user_service_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogOutV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogOutV1Request) ProtoMessage() {}

func (x *LogOutV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogOutV1Request.ProtoReflect.Descriptor instead.
func (*LogOutV1Request) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{4}
}

type LogOutV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogOutV1Response) Reset() {
	*x = LogOutV1Response{}
	mi := &file_user_service_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogOutV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogOutV1Response) ProtoMessage() {}

func (x *LogOutV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogOutV1Response.ProtoReflect.Descriptor instead.
func (*LogOutV1Response) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{5}
}

type UpdateV1Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateV1Request) Reset() {
	*x = UpdateV1Request{}
	mi := &file_user_service_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateV1Request) ProtoMessage() {}

func (x *UpdateV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateV1Request.ProtoReflect.Descriptor instead.
func (*UpdateV1Request) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{6}
}

type UpdateV1Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateV1Response) Reset() {
	*x = UpdateV1Response{}
	mi := &file_user_service_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateV1Response) ProtoMessage() {}

func (x *UpdateV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateV1Response.ProtoReflect.Descriptor instead.
func (*UpdateV1Response) Descriptor() ([]byte, []int) {
	return file_user_service_user_service_proto_rawDescGZIP(), []int{7}
}

var File_user_service_user_service_proto protoreflect.FileDescriptor

const file_user_service_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1fuser_service/user_service.proto\x12\fchat_service\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fSignUpV1Request\"\x12\n" +
	"\x10SignUpV1Response\"\x10\n" +
	"\x0eLogInV1Request\"\x11\n" +
	"\x0fLogInV1Response\"\x11\n" +
	"\x0fLogOutV1Request\"\x12\n" +
	"\x10LogOutV1Response\"\x11\n" +
	"\x0fUpdateV1Request\"\x12\n" +
	"\x10UpdateV1Response2\x91\x03\n" +
	"\vUserService\x12`\n" +
	"\bSignUpV1\x12\x1d.chat_service.SignUpV1Request\x1a\x1e.chat_service.SignUpV1Response\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/signup\x12\\\n" +
	"\aLogInV1\x12\x1c.chat_service.LogInV1Request\x1a\x1d.chat_service.LogInV1Response\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login\x12`\n" +
	"\bLogOutV1\x12\x1d.chat_service.LogOutV1Request\x1a\x1e.chat_service.LogOutV1Response\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/logout\x12`\n" +
	"\bUpdateV1\x12\x1d.chat_service.UpdateV1Request\x1a\x1e.chat_service.UpdateV1Response\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/updateB*Z(chattery/user_service/api;user_servicepbb\x06proto3"

var (
	file_user_service_user_service_proto_rawDescOnce sync.Once
	file_user_service_user_service_proto_rawDescData []byte
)

func file_user_service_user_service_proto_rawDescGZIP() []byte {
	file_user_service_user_service_proto_rawDescOnce.Do(func() {
		file_user_service_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_user_service_proto_rawDesc), len(file_user_service_user_service_proto_rawDesc)))
	})
	return file_user_service_user_service_proto_rawDescData
}

var file_user_service_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_service_user_service_proto_goTypes = []any{
	(*SignUpV1Request)(nil),  // 0: chat_service.SignUpV1Request
	(*SignUpV1Response)(nil), // 1: chat_service.SignUpV1Response
	(*LogInV1Request)(nil),   // 2: chat_service.LogInV1Request
	(*LogInV1Response)(nil),  // 3: chat_service.LogInV1Response
	(*LogOutV1Request)(nil),  // 4: chat_service.LogOutV1Request
	(*LogOutV1Response)(nil), // 5: chat_service.LogOutV1Response
	(*UpdateV1Request)(nil),  // 6: chat_service.UpdateV1Request
	(*UpdateV1Response)(nil), // 7: chat_service.UpdateV1Response
}
var file_user_service_user_service_proto_depIdxs = []int32{
	0, // 0: chat_service.UserService.SignUpV1:input_type -> chat_service.SignUpV1Request
	2, // 1: chat_service.UserService.LogInV1:input_type -> chat_service.LogInV1Request
	4, // 2: chat_service.UserService.LogOutV1:input_type -> chat_service.LogOutV1Request
	6, // 3: chat_service.UserService.UpdateV1:input_type -> chat_service.UpdateV1Request
	1, // 4: chat_service.UserService.SignUpV1:output_type -> chat_service.SignUpV1Response
	3, // 5: chat_service.UserService.LogInV1:output_type -> chat_service.LogInV1Response
	5, // 6: chat_service.UserService.LogOutV1:output_type -> chat_service.LogOutV1Response
	7, // 7: chat_service.UserService.UpdateV1:output_type -> chat_service.UpdateV1Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_user_service_proto_init() }
func file_user_service_user_service_proto_init() {
	if File_user_service_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_user_service_proto_rawDesc), len(file_user_service_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_user_service_proto_depIdxs,
		MessageInfos:      file_user_service_user_service_proto_msgTypes,
	}.Build()
	File_user_service_user_service_proto = out.File
	file_user_service_user_service_proto_goTypes = nil
	file_user_service_user_service_proto_depIdxs = nil
}
