// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: user_service/user_service.proto

package user_servicepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_SignUpV1_FullMethodName = "/chat_service.UserService/SignUpV1"
	UserService_LogInV1_FullMethodName  = "/chat_service.UserService/LogInV1"
	UserService_LogOutV1_FullMethodName = "/chat_service.UserService/LogOutV1"
	UserService_UpdateV1_FullMethodName = "/chat_service.UserService/UpdateV1"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	SignUpV1(ctx context.Context, in *SignUpV1Request, opts ...grpc.CallOption) (*SignUpV1Response, error)
	LogInV1(ctx context.Context, in *LogInV1Request, opts ...grpc.CallOption) (*LogInV1Response, error)
	LogOutV1(ctx context.Context, in *LogOutV1Request, opts ...grpc.CallOption) (*LogOutV1Response, error)
	UpdateV1(ctx context.Context, in *UpdateV1Request, opts ...grpc.CallOption) (*UpdateV1Response, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) SignUpV1(ctx context.Context, in *SignUpV1Request, opts ...grpc.CallOption) (*SignUpV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignUpV1Response)
	err := c.cc.Invoke(ctx, UserService_SignUpV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LogInV1(ctx context.Context, in *LogInV1Request, opts ...grpc.CallOption) (*LogInV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogInV1Response)
	err := c.cc.Invoke(ctx, UserService_LogInV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) LogOutV1(ctx context.Context, in *LogOutV1Request, opts ...grpc.CallOption) (*LogOutV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogOutV1Response)
	err := c.cc.Invoke(ctx, UserService_LogOutV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateV1(ctx context.Context, in *UpdateV1Request, opts ...grpc.CallOption) (*UpdateV1Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateV1Response)
	err := c.cc.Invoke(ctx, UserService_UpdateV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
type UserServiceServer interface {
	SignUpV1(context.Context, *SignUpV1Request) (*SignUpV1Response, error)
	LogInV1(context.Context, *LogInV1Request) (*LogInV1Response, error)
	LogOutV1(context.Context, *LogOutV1Request) (*LogOutV1Response, error)
	UpdateV1(context.Context, *UpdateV1Request) (*UpdateV1Response, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) SignUpV1(context.Context, *SignUpV1Request) (*SignUpV1Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SignUpV1 not implemented")
}
func (UnimplementedUserServiceServer) LogInV1(context.Context, *LogInV1Request) (*LogInV1Response, error) {
	return nil, status.Error(codes.Unimplemented, "method LogInV1 not implemented")
}
func (UnimplementedUserServiceServer) LogOutV1(context.Context, *LogOutV1Request) (*LogOutV1Response, error) {
	return nil, status.Error(codes.Unimplemented, "method LogOutV1 not implemented")
}
func (UnimplementedUserServiceServer) UpdateV1(context.Context, *UpdateV1Request) (*UpdateV1Response, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateV1 not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_SignUpV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SignUpV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SignUpV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SignUpV1(ctx, req.(*SignUpV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LogInV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogInV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LogInV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LogInV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LogInV1(ctx, req.(*LogInV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_LogOutV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogOutV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).LogOutV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_LogOutV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).LogOutV1(ctx, req.(*LogOutV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateV1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateV1(ctx, req.(*UpdateV1Request))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat_service.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUpV1",
			Handler:    _UserService_SignUpV1_Handler,
		},
		{
			MethodName: "LogInV1",
			Handler:    _UserService_LogInV1_Handler,
		},
		{
			MethodName: "LogOutV1",
			Handler:    _UserService_LogOutV1_Handler,
		},
		{
			MethodName: "UpdateV1",
			Handler:    _UserService_UpdateV1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_service/user_service.proto",
}
