// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres_client

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64
	Login     string
	Password  []byte
	Username  string
	ImageID   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
