// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package postgres_client

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, login, password, username, image_id, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.Password,
		&i.Username,
		&i.ImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users(login, password, username)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertUserParams struct {
	Login    string
	Password []byte
	Username string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Login, arg.Password, arg.Username)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET login=$2,
    password=$3,
    username=$4,
    image_id=$5,
    updated_at=now()
WHERE id=$1
`

type UpdateUserParams struct {
	ID       int64
	Login    string
	Password []byte
	Username string
	ImageID  string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Login,
		arg.Password,
		arg.Username,
		arg.ImageID,
	)
	return err
}
