// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: websocket/websocket.proto

package websocketpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_ENUM_TYPE_UNDEFINED        Type = 0
	Type_ENUM_TYPE_JOIN_CHAT        Type = 1
	Type_ENUM_TYPE_LEAVE_CHAT       Type = 2
	Type_ENUM_TYPE_ICE_CANDIDATE    Type = 3
	Type_ENUM_TYPE_OFFER            Type = 4
	Type_ENUM_TYPE_ANSWER           Type = 5
	Type_ENUM_TYPE_JOIN_ROOM        Type = 6
	Type_ENUM_TYPE_LEAVE_ROOM       Type = 7
	Type_ENUM_TYPE_USER_JOINED_ROOM Type = 8
	Type_ENUM_TYPE_USER_LEAVED_ROOM Type = 9
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "ENUM_TYPE_UNDEFINED",
		1: "ENUM_TYPE_JOIN_CHAT",
		2: "ENUM_TYPE_LEAVE_CHAT",
		3: "ENUM_TYPE_ICE_CANDIDATE",
		4: "ENUM_TYPE_OFFER",
		5: "ENUM_TYPE_ANSWER",
		6: "ENUM_TYPE_JOIN_ROOM",
		7: "ENUM_TYPE_LEAVE_ROOM",
		8: "ENUM_TYPE_USER_JOINED_ROOM",
		9: "ENUM_TYPE_USER_LEAVED_ROOM",
	}
	Type_value = map[string]int32{
		"ENUM_TYPE_UNDEFINED":        0,
		"ENUM_TYPE_JOIN_CHAT":        1,
		"ENUM_TYPE_LEAVE_CHAT":       2,
		"ENUM_TYPE_ICE_CANDIDATE":    3,
		"ENUM_TYPE_OFFER":            4,
		"ENUM_TYPE_ANSWER":           5,
		"ENUM_TYPE_JOIN_ROOM":        6,
		"ENUM_TYPE_LEAVE_ROOM":       7,
		"ENUM_TYPE_USER_JOINED_ROOM": 8,
		"ENUM_TYPE_USER_LEAVED_ROOM": 9,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_websocket_websocket_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_websocket_websocket_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  Type                   `protobuf:"varint,2,opt,name=type,proto3,enum=websocket.Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*Message_JoinChat
	//	*Message_LeaveChat
	//	*Message_IceCandidate
	//	*Message_Offer
	//	*Message_Answer
	//	*Message_JoinRoom
	//	*Message_LeaveRoom
	//	*Message_UserJoinedRoom
	//	*Message_UserLeavedRoom
	Content       isMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_websocket_websocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_ENUM_TYPE_UNDEFINED
}

func (x *Message) GetContent() isMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Message) GetJoinChat() *JoinChat {
	if x != nil {
		if x, ok := x.Content.(*Message_JoinChat); ok {
			return x.JoinChat
		}
	}
	return nil
}

func (x *Message) GetLeaveChat() *LeaveChat {
	if x != nil {
		if x, ok := x.Content.(*Message_LeaveChat); ok {
			return x.LeaveChat
		}
	}
	return nil
}

func (x *Message) GetIceCandidate() *IceCandidate {
	if x != nil {
		if x, ok := x.Content.(*Message_IceCandidate); ok {
			return x.IceCandidate
		}
	}
	return nil
}

func (x *Message) GetOffer() *Offer {
	if x != nil {
		if x, ok := x.Content.(*Message_Offer); ok {
			return x.Offer
		}
	}
	return nil
}

func (x *Message) GetAnswer() *Answer {
	if x != nil {
		if x, ok := x.Content.(*Message_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *Message) GetJoinRoom() *JoinRoom {
	if x != nil {
		if x, ok := x.Content.(*Message_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *Message) GetLeaveRoom() *LeaveRoom {
	if x != nil {
		if x, ok := x.Content.(*Message_LeaveRoom); ok {
			return x.LeaveRoom
		}
	}
	return nil
}

func (x *Message) GetUserJoinedRoom() *UserJoinedRoom {
	if x != nil {
		if x, ok := x.Content.(*Message_UserJoinedRoom); ok {
			return x.UserJoinedRoom
		}
	}
	return nil
}

func (x *Message) GetUserLeavedRoom() *UserLeavedRoom {
	if x != nil {
		if x, ok := x.Content.(*Message_UserLeavedRoom); ok {
			return x.UserLeavedRoom
		}
	}
	return nil
}

type isMessage_Content interface {
	isMessage_Content()
}

type Message_JoinChat struct {
	JoinChat *JoinChat `protobuf:"bytes,3,opt,name=join_chat,json=joinChat,proto3,oneof"`
}

type Message_LeaveChat struct {
	LeaveChat *LeaveChat `protobuf:"bytes,4,opt,name=leave_chat,json=leaveChat,proto3,oneof"`
}

type Message_IceCandidate struct {
	IceCandidate *IceCandidate `protobuf:"bytes,5,opt,name=ice_candidate,json=iceCandidate,proto3,oneof"`
}

type Message_Offer struct {
	Offer *Offer `protobuf:"bytes,6,opt,name=offer,proto3,oneof"`
}

type Message_Answer struct {
	Answer *Answer `protobuf:"bytes,7,opt,name=answer,proto3,oneof"`
}

type Message_JoinRoom struct {
	JoinRoom *JoinRoom `protobuf:"bytes,8,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type Message_LeaveRoom struct {
	LeaveRoom *LeaveRoom `protobuf:"bytes,9,opt,name=leave_room,json=leaveRoom,proto3,oneof"`
}

type Message_UserJoinedRoom struct {
	UserJoinedRoom *UserJoinedRoom `protobuf:"bytes,10,opt,name=user_joined_room,json=userJoinedRoom,proto3,oneof"`
}

type Message_UserLeavedRoom struct {
	UserLeavedRoom *UserLeavedRoom `protobuf:"bytes,11,opt,name=user_leaved_room,json=userLeavedRoom,proto3,oneof"`
}

func (*Message_JoinChat) isMessage_Content() {}

func (*Message_LeaveChat) isMessage_Content() {}

func (*Message_IceCandidate) isMessage_Content() {}

func (*Message_Offer) isMessage_Content() {}

func (*Message_Answer) isMessage_Content() {}

func (*Message_JoinRoom) isMessage_Content() {}

func (*Message_LeaveRoom) isMessage_Content() {}

func (*Message_UserJoinedRoom) isMessage_Content() {}

func (*Message_UserLeavedRoom) isMessage_Content() {}

type JoinChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinChat) Reset() {
	*x = JoinChat{}
	mi := &file_websocket_websocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinChat) ProtoMessage() {}

func (x *JoinChat) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinChat.ProtoReflect.Descriptor instead.
func (*JoinChat) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *JoinChat) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type LeaveChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveChat) Reset() {
	*x = LeaveChat{}
	mi := &file_websocket_websocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveChat) ProtoMessage() {}

func (x *LeaveChat) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveChat.ProtoReflect.Descriptor instead.
func (*LeaveChat) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *LeaveChat) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type SendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	mi := &file_websocket_websocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *SendMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ReceiveMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveMessage) Reset() {
	*x = ReceiveMessage{}
	mi := &file_websocket_websocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMessage) ProtoMessage() {}

func (x *ReceiveMessage) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMessage.ProtoReflect.Descriptor instead.
func (*ReceiveMessage) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiveMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ReceiveMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type IceCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IceCandidate) Reset() {
	*x = IceCandidate{}
	mi := &file_websocket_websocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCandidate) ProtoMessage() {}

func (x *IceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCandidate.ProtoReflect.Descriptor instead.
func (*IceCandidate) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{5}
}

type Offer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Offer) Reset() {
	*x = Offer{}
	mi := &file_websocket_websocket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{6}
}

type Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_websocket_websocket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{7}
}

type JoinRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	mi := &file_websocket_websocket_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRoom) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type LeaveRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomID        string                 `protobuf:"bytes,1,opt,name=RoomID,proto3" json:"RoomID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoom) Reset() {
	*x = LeaveRoom{}
	mi := &file_websocket_websocket_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoom) ProtoMessage() {}

func (x *LeaveRoom) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoom.ProtoReflect.Descriptor instead.
func (*LeaveRoom) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveRoom) GetRoomID() string {
	if x != nil {
		return x.RoomID
	}
	return ""
}

type UserJoinedRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserJoinedRoom) Reset() {
	*x = UserJoinedRoom{}
	mi := &file_websocket_websocket_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserJoinedRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJoinedRoom) ProtoMessage() {}

func (x *UserJoinedRoom) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJoinedRoom.ProtoReflect.Descriptor instead.
func (*UserJoinedRoom) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{10}
}

type UserLeavedRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLeavedRoom) Reset() {
	*x = UserLeavedRoom{}
	mi := &file_websocket_websocket_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLeavedRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLeavedRoom) ProtoMessage() {}

func (x *UserLeavedRoom) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_websocket_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLeavedRoom.ProtoReflect.Descriptor instead.
func (*UserLeavedRoom) Descriptor() ([]byte, []int) {
	return file_websocket_websocket_proto_rawDescGZIP(), []int{11}
}

var File_websocket_websocket_proto protoreflect.FileDescriptor

const file_websocket_websocket_proto_rawDesc = "" +
	"\n" +
	"\x19websocket/websocket.proto\x12\twebsocket\"\xc4\x04\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\x04type\x18\x02 \x01(\x0e2\x0f.websocket.TypeR\x04type\x122\n" +
	"\tjoin_chat\x18\x03 \x01(\v2\x13.websocket.JoinChatH\x00R\bjoinChat\x125\n" +
	"\n" +
	"leave_chat\x18\x04 \x01(\v2\x14.websocket.LeaveChatH\x00R\tleaveChat\x12>\n" +
	"\rice_candidate\x18\x05 \x01(\v2\x17.websocket.IceCandidateH\x00R\ficeCandidate\x12(\n" +
	"\x05offer\x18\x06 \x01(\v2\x10.websocket.OfferH\x00R\x05offer\x12+\n" +
	"\x06answer\x18\a \x01(\v2\x11.websocket.AnswerH\x00R\x06answer\x122\n" +
	"\tjoin_room\x18\b \x01(\v2\x13.websocket.JoinRoomH\x00R\bjoinRoom\x125\n" +
	"\n" +
	"leave_room\x18\t \x01(\v2\x14.websocket.LeaveRoomH\x00R\tleaveRoom\x12E\n" +
	"\x10user_joined_room\x18\n" +
	" \x01(\v2\x19.websocket.UserJoinedRoomH\x00R\x0euserJoinedRoom\x12E\n" +
	"\x10user_leaved_room\x18\v \x01(\v2\x19.websocket.UserLeavedRoomH\x00R\x0euserLeavedRoomB\t\n" +
	"\acontent\"#\n" +
	"\bJoinChat\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"$\n" +
	"\tLeaveChat\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"@\n" +
	"\vSendMessage\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"C\n" +
	"\x0eReceiveMessage\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x0e\n" +
	"\fIceCandidate\"\a\n" +
	"\x05Offer\"\b\n" +
	"\x06Answer\"\"\n" +
	"\bJoinRoom\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\tR\x06RoomID\"#\n" +
	"\tLeaveRoom\x12\x16\n" +
	"\x06RoomID\x18\x01 \x01(\tR\x06RoomID\"\x10\n" +
	"\x0eUserJoinedRoom\"\x10\n" +
	"\x0eUserLeavedRoom*\x8d\x02\n" +
	"\x04Type\x12\x17\n" +
	"\x13ENUM_TYPE_UNDEFINED\x10\x00\x12\x17\n" +
	"\x13ENUM_TYPE_JOIN_CHAT\x10\x01\x12\x18\n" +
	"\x14ENUM_TYPE_LEAVE_CHAT\x10\x02\x12\x1b\n" +
	"\x17ENUM_TYPE_ICE_CANDIDATE\x10\x03\x12\x13\n" +
	"\x0fENUM_TYPE_OFFER\x10\x04\x12\x14\n" +
	"\x10ENUM_TYPE_ANSWER\x10\x05\x12\x17\n" +
	"\x13ENUM_TYPE_JOIN_ROOM\x10\x06\x12\x18\n" +
	"\x14ENUM_TYPE_LEAVE_ROOM\x10\a\x12\x1e\n" +
	"\x1aENUM_TYPE_USER_JOINED_ROOM\x10\b\x12\x1e\n" +
	"\x1aENUM_TYPE_USER_LEAVED_ROOM\x10\tB\x11Z\x0fapi/websocketpbb\x06proto3"

var (
	file_websocket_websocket_proto_rawDescOnce sync.Once
	file_websocket_websocket_proto_rawDescData []byte
)

func file_websocket_websocket_proto_rawDescGZIP() []byte {
	file_websocket_websocket_proto_rawDescOnce.Do(func() {
		file_websocket_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_websocket_websocket_proto_rawDesc), len(file_websocket_websocket_proto_rawDesc)))
	})
	return file_websocket_websocket_proto_rawDescData
}

var file_websocket_websocket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_websocket_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_websocket_websocket_proto_goTypes = []any{
	(Type)(0),              // 0: websocket.Type
	(*Message)(nil),        // 1: websocket.Message
	(*JoinChat)(nil),       // 2: websocket.JoinChat
	(*LeaveChat)(nil),      // 3: websocket.LeaveChat
	(*SendMessage)(nil),    // 4: websocket.SendMessage
	(*ReceiveMessage)(nil), // 5: websocket.ReceiveMessage
	(*IceCandidate)(nil),   // 6: websocket.IceCandidate
	(*Offer)(nil),          // 7: websocket.Offer
	(*Answer)(nil),         // 8: websocket.Answer
	(*JoinRoom)(nil),       // 9: websocket.JoinRoom
	(*LeaveRoom)(nil),      // 10: websocket.LeaveRoom
	(*UserJoinedRoom)(nil), // 11: websocket.UserJoinedRoom
	(*UserLeavedRoom)(nil), // 12: websocket.UserLeavedRoom
}
var file_websocket_websocket_proto_depIdxs = []int32{
	0,  // 0: websocket.Message.type:type_name -> websocket.Type
	2,  // 1: websocket.Message.join_chat:type_name -> websocket.JoinChat
	3,  // 2: websocket.Message.leave_chat:type_name -> websocket.LeaveChat
	6,  // 3: websocket.Message.ice_candidate:type_name -> websocket.IceCandidate
	7,  // 4: websocket.Message.offer:type_name -> websocket.Offer
	8,  // 5: websocket.Message.answer:type_name -> websocket.Answer
	9,  // 6: websocket.Message.join_room:type_name -> websocket.JoinRoom
	10, // 7: websocket.Message.leave_room:type_name -> websocket.LeaveRoom
	11, // 8: websocket.Message.user_joined_room:type_name -> websocket.UserJoinedRoom
	12, // 9: websocket.Message.user_leaved_room:type_name -> websocket.UserLeavedRoom
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_websocket_websocket_proto_init() }
func file_websocket_websocket_proto_init() {
	if File_websocket_websocket_proto != nil {
		return
	}
	file_websocket_websocket_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_JoinChat)(nil),
		(*Message_LeaveChat)(nil),
		(*Message_IceCandidate)(nil),
		(*Message_Offer)(nil),
		(*Message_Answer)(nil),
		(*Message_JoinRoom)(nil),
		(*Message_LeaveRoom)(nil),
		(*Message_UserJoinedRoom)(nil),
		(*Message_UserLeavedRoom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_websocket_websocket_proto_rawDesc), len(file_websocket_websocket_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_websocket_websocket_proto_goTypes,
		DependencyIndexes: file_websocket_websocket_proto_depIdxs,
		EnumInfos:         file_websocket_websocket_proto_enumTypes,
		MessageInfos:      file_websocket_websocket_proto_msgTypes,
	}.Build()
	File_websocket_websocket_proto = out.File
	file_websocket_websocket_proto_goTypes = nil
	file_websocket_websocket_proto_depIdxs = nil
}
